<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>

    <!--You can use the .NET Framework 4.7 build to execute the application on Linux/Mono-->
    <TargetFrameworks>net10.0-windows;net47</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <!--Suppressions
      - WFO0003: Remove high DPI settings from app.manifest - intended, not every targeted platform supports the new alternatives.
    -->
    <NoWarn>$(NoWarn);WFO1000;WFO0003;WFAC010;NETSDK1138</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!--This implicitly references KGySoft.Drawing as well-->
    <PackageReference Include="KGySoft.WinForms" Version="5.0.0" />
  </ItemGroup>

  <Import Project="..\_Shared\KGySoft.Drawing.Examples.Shared.projitems" Label="Shared" />

</Project>